# Swagger UI
%dev.quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.always-include=false
quarkus.swagger-ui.path=/swagger-ui

# Tennis API
mp.openapi.extensions.smallrye.info.title=Tennis API 
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Tennis league, match, and standings management API.

quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false

# TESTCONTAINERS
%dev.quarkus.devservices.enabled=false
%dev.quarkus.oidc.devservices.enabled=false
%dev.quarkus.aws.devservices.enabled=false

# POSTGRESQL & FLYWAY (ENVIRONMENT VARIABLES)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

# RE-CLIENT URL (Reactive Pipeline)
quarkus.datasource.reactive=true
%dev.quarkus.datasource.reactive.url=vertx-reactive:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
%prod.quarkus.datasource.reactive.url=vertx-reactive:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
%prod.quarkus.datasource.reactive.max-size=2
%prod.quarkus.datasource.reactive.idle-timeout=10s
quarkus.native.resources.includes=certs/us-east-1-bundle.pem

quarkus.datasource.reactive.ssl-mode=${SSL_MODE:PREFER}
quarkus.datasource.reactive.postgresql.ssl-mode=${SSL_POSTGRESQL:require}

# JDBC URL Flyway/Panache (Blocking Pipeline)
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
%dev.quarkus.hibernate-reactive.database.generation=none

# FLYWAY AUTOMATION
%dev.quarkus.datasource.jdbc=true
%dev.quarkus.flyway.baseline-version=0
%dev.quarkus.flyway.migrate-at-start=true

# SERVERLESS / AWS LAMBDA
quarkus.security.auth.enabled-in-dev-mode=false
quarkus.vertx.worker-pool-size=20
quarkus.vertx.prefer-native-transport=true

# CORS CONFIGURATION
quarkus.http.cors=true
quarkus.http.cors.origins=${FRONTEND_URL}
quarkus.http.cors.headers=accept, authorization, content-type
quarkus.http.cors.methods=GET, POST, PUT, PATCH, DELETE, OPTIONS

# OIDC GLOBAL
quarkus.oidc.application-type=service

# DEVELOPMENT (KEYCLOAK)
%dev.quarkus.security.auth.enabled-in-dev-mode=false
%dev.quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:http://localhost:8180/realms/quarkus}
%dev.quarkus.oidc.credentials.secret=${QUARKUS_OIDC_CREDENTIALS_SECRET}

# PRODUCTION (AWS COGNITO)
%prod.quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:https://cognito-idp.${AWS_REGION:us-east-1}.amazonaws.com/${COGNITO_USER_POOL_ID}}
quarkus.oidc.client-id=${OICD_CLIENT_ID:backend-service}
quarkus.oidc.roles.role-claim-path=${ROLE_CLAIM_PATH:cognito:groups}

# HTTP Render.com configuration
quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}

# UPX 
quarkus.native.enable-upx=true