# Swagger UI
%dev.quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.always-include=false
quarkus.swagger-ui.path=/swagger-ui

# Tennis API
mp.openapi.extensions.smallrye.info.title=Tennis API 
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Tennis league, match, and standings management API.

quarkus.http.port=8080

quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false

# TESTCONTAINERS
%dev.quarkus.devservices.enabled=false
%dev.quarkus.oidc.devservices.enabled=false
%dev.quarkus.aws.devservices.enabled=false

# POSTGRESQL & FLYWAY (ENVIRONMENT VARIABLES)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

# RE-CLIENT URL (Reactive Pipeline)
quarkus.datasource.reactive=true
quarkus.datasource.reactive.url=vertx-reactive:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
%prod.quarkus.datasource.reactive.max-size=2
%prod.quarkus.datasource.reactive.idle-timeout=10s
%prod.quarkus.datasource.reactive.postgresql.ssl-mode=verify-full
%prod.quarkus.datasource.reactive.hostname-verification-algorithm=HTTPS
%prod.quarkus.datasource.reactive.client.trust-certificate-pem=true
%prod.quarkus.datasource.reactive.client.trust-certificate-pem.certs=certs/us-east-1-bundle.pem

# JDBC URL Flyway/Panache (Blocking Pipeline)
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
%dev.quarkus.hibernate-reactive.database.generation=none

# FLYWAY AUTOMATION
%dev.quarkus.datasource.jdbc=true
%dev.quarkus.flyway.baseline-version=0
%dev.quarkus.flyway.migrate-at-start=true

# SERVERLESS / AWS LAMBDA
quarkus.security.auth.enabled-in-dev-mode=false
quarkus.vertx.worker-pool-size=20
quarkus.vertx.prefer-native-transport=true

# CORS CONFIGURATION
quarkus.http.cors=true
quarkus.http.cors.origins=${FRONTEND_URL}
quarkus.http.cors.headers=accept, authorization, content-type
quarkus.http.cors.methods=GET, POST, PUT, PATCH, DELETE, OPTIONS

# OIDC GLOBAL
quarkus.oidc.application-type=service

# DEVELOPMENT (KEYCLOAK)
%dev.quarkus.security.auth.enabled-in-dev-mode=false
%dev.quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
%dev.quarkus.oidc.client-id=backend-service
%dev.quarkus.oidc.roles.role-claim-path=realm_access/roles

# PRODUCTION (AWS COGNITO)
%prod.quarkus.oidc.auth-server-url=https://cognito-idp.${AWS_REGION:us-east-1}.amazonaws.com/${COGNITO_USER_POOL_ID}
%prod.quarkus.oidc.client-id=${COGNITO_CLIENT_ID}
%prod.quarkus.oidc.roles.role-claim-path=cognito:groups