FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

WORKDIR /work/

COPY --chown=1001:root --chmod=0755 target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]